import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Image from 'next/image';
import LogoSvg from '../app/assets/logo.svg';
import Link from 'next/link';
import Footer from "@/components/footer";


const pretendard = localFont({
  src: "./fonts/PretendardVariable.woff2",
  variable: "--font-pretendard",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={pretendard.variable}>
        <main className="font-pretendard min-h-screen">
        {/* Header */}
          <header className="sticky top-0 z-10 shadow-md backdrop-filter backdrop-blur-lg bg-opacity-30">
          <div className="bg-white flex items-center justify-center bg-opacity-30">
                <Link href={'/'}>
                <Image src={LogoSvg} alt="logo" className="my-3 max-w-10 m-auto"/>
                </Link>
            </div>
          </header>
        {/* Main Section */}
          <section className="min-h-screen flex-grow max-w-[700px] m-auto">
            {children}
          </section>
        {/* Footer */}
         <Footer />
        </main>
      </body>
    </html>
  );
}